version: "3.8"

services:
  mariadb:
    build: ./srcs/mariadb
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    build: ./srcs/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

  wordpress:
    build: ./srcs/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_N=${WP_ADMIN_N}
      - WP_ADMIN_P=${WP_ADMIN_P}
      - WP_ADMIN_E=${WP_ADMIN_E}
      - WP_U_NAME=${WP_U_NAME}
      - WP_U_PASS=${WP_U_PASS}
      - WP_U_ROLE=${WP_U_ROLE}
      - WP_U_EMAIL=${WP_U_EMAIL}
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - inception
    healthcheck:
      test: ["CMD", "pidof", "php-fpm7.4"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/eghaffar/data/mariadb
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/eghaffar/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge
